apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}                  
  selector:                    
    matchLabels:
      app: {{ .Values.podLabel }}          

  # Pod template
  template:
    metadata:
      name: {{ .Values.podname }}                
      labels:
        app: {{ .Values.podLabel }}   
    spec:
      containers:                       
        - name: {{ .Values.containerName }}                     
          image: {{ .Values.imageVersion }} # minhpq331/demo-service   
          imagePullPolicy: {{ .Values.imagePullPolicy }} 
          env:
            - name: PORT
              value: "{{ .Values.appPort }}"

            - name: MONGODB_URI
              value: "{{ .Values.mongoUrl }}" # mongodb://test-db:3000/app      
