apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}         # Virtual IP + map host port
  selector:
    app:  {{ .Values.podLabel }}        # Label selector
  ports:
    - protocol: TCP      # Protocol
      port: {{ .Values.servicePort }}           # Port của service
      targetPort: {{ .Values.appPort }}   # Port của pod
      nodePort: {{ .Values.nodePort }}    # Port của host (optional)
