apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  completions: 6
  parallelism: 3
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: job
        image: luksa/batch-job 
      restartPolicy: OnFailure   
