apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: java
spec:
  replicas: 5
  minReadySeconds: 10
  selector:                        
    matchLabels:                    
      app: java  
  strategy:
    type: RollingUpdate             
    rollingUpdate:                   
      maxUnavailable: 2              
      maxSurge: 2                 
  template:
    metadata:
      labels:                              
        app: java                     
    spec:                                   
      containers:
      - name: nginx                
        image: nginx:latest
        ports:
        - containerPort: 80 
