apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: nodejs
spec:
  replicas: 3                  
  selector:                    
    matchLabels:
      app: nodejs          

  # Pod template
  template:
    metadata:
      name: node-pod                
      labels:
        app: nodejs        # Pod labels
    spec:
      containers:                       
        - name: node-app                     
          image: minhpq331/demo-service   
          imagePullPolicy: Always 
          env:
            - name: PORT
              value: 5000

            - name: MONGODB_URI
              value: mongodb://test-db:3000/app      
