apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort         # Virtual IP + map host port
  selector:
    app: nodejs       # Label selector
  ports:
    - protocol: TCP      # Protocol
      port: 80           # Port của service
      targetPort: 5000   # Port của pod
      nodePort: 30007    # Port của host (optional)
