apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: whoami
      labels:
        app: frontend
    spec:
      containers:
      - name: whoami
        image: jwilder/whoami
        ports:
        - containerPort: 80
