apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}        
  selector:
    db: {{ .Values.podLabel }}
  ports:
    - protocol: TCP      
      port: {{ .Values.servicePort }}           
      targetPort: {{ .Values.podPort }}
